### ISSUE TITLE
[Bug Report] vuetify-loader loading in Expension Panel error

### ISSUE THREAD

**Issue by donthijackthegit** [vuetifyjs/vuetify-loader#88] opened 2019-09-19 03:07 UTC
**Environment**
Vuetify Version: 2.0.17
Vue Version: 2.6.10
Browsers: Chrome 76.0.3809.132
OS: Mac OS 10.14.6

**Steps to reproduce**
webpack@^4.39.3, in webpack.conf.js

```
plugins: [
                ...
		new VuetifyLoaderPlugin(),
                ...
	]
```

in a .vue file tag:
```
<v-expansion-panels
      v-model="panel"
      :disabled="disabled"
      multiple
    >
      <v-expansion-panel>
        <v-expansion-panel-header>Panel 1</v-expansion-panel-header>
        <v-expansion-panel-content>
          Some content
        </v-expansion-panel-content>
      </v-expansion-panel>

      <v-expansion-panel>
        <v-expansion-panel-header>Panel 2</v-expansion-panel-header>
        <v-expansion-panel-content>
          Some content
        </v-expansion-panel-content>
      </v-expansion-panel>

      <v-expansion-panel>
        <v-expansion-panel-header>Panel 3</v-expansion-panel-header>
        <v-expansion-panel-content>
          Some content
        </v-expansion-panel-content>
      </v-expansion-panel>
    </v-expansion-panels>
```
Compilation is successful, but in runtime webpack-dev-server throw errors and warnings.

**Expected Behavior**
vuetify-loader loads vuetify components correctly

**Actual Behavior**
page broken, in console:

- A warning shows "v-expansion-panel should wrapped in v-expansion-panels"
- this.expansionPanel.registerContent is not a function

**Other comments**
Seems vuetify-loader only loads the v-expansion-panel but not other dependencies, I have to disable vuetify-loader and use below as workaround
```
import Vuetify, {
	VExpansionPanel,
	VExpansionPanels,
	VExpansionPanelContent,
	VExpansionPanelHeader,
} from 'vuetify/lib';

Vue.use(Vuetify, {
	components: {
		VExpansionPanel,
		VExpansionPanels,
		VExpansionPanelContent,
		VExpansionPanelHeader,
	},
});
```

**Comment by KaelWD** [comment] 2019-11-12 10:49
Closing due to lack of reproduction, I haven't seen anything like this myself.

**Closed by KaelWD** 2019-11-12 10:49 UTC
Labels: need reproduction

**Comment by roxburghm** [comment] 2020-02-21 14:45
Hi, just my 2c worth.

I've seen this happening during a migration.

When you are changing the markup from

                        <template v-slot:header>
                            ...
                        </template>

to

                        <v-expansion-panel-header>
                            ...
                        </v-expansion-panel-header>

It seems to throw a wobbler.  I've seen far less of it now by removing the <tempate v-slot:header> saving, letting it recompile and then adding the v-expansion-panel-header.

Sometimes remove the template header and wrap the content in the v-expansion-panel-content save, let it recompile and then insert the header.

Very weird but it's something to do with the migration process.

**Comment by leokolezhuk** [comment] 2022-05-23 15:21
Not sure if it is exactly the same as the original issue, but I have the same symptoms:

https://github.com/leokolezhuk/vuetify-wrap-problem
(Sorry the repo is a bit messy, but the idea is that there is a library that wraps the expansion panel components of vuetify; and there is an app that uses these components of the library) 

The app raises a lot of errors such as described above.

Interestingly, if I add the wrapped components to the app itself, it works fine.
When built as part of the library and and then used elsewhere, the trouble starts.
I suspect something goes wrong during the bundling, but cannot understand what exaclty.
