### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by ImFranQ** [vuetifyjs/vuetify-loader#214] opened 2021-10-17 00:44 UTC
The error occurs when I run `yarn serve` command after installing vuetify 3 by CLI.

Error log
![image](https://user-images.githubusercontent.com/8723165/137605701-9923c09d-ae4b-49ed-bd34-2354dd842cbd.png)s

```
{
"dependencies": {
    "@mdi/font": "5.9.55",
    "core-js": "^3.6.5",
    "roboto-fontface": "*",
    "vue": "^3.0.0",
    "vuetify": "^3.0.0-alpha.0",
    "webfontloader": "^1.0.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~5.0.0-beta.3",
    "@vue/compiler-sfc": "^3.0.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0",
    "sass": "^1.38.0",
    "sass-loader": "^10.0.0",
    "vue-cli-plugin-vuetify": "~2.4.3",
    "vuetify-loader": "^2.0.0-alpha.0"
  },
}
```

**Comment by KaelWD** [comment] 2021-10-17 04:37
Duplicate of #212

**Closed by KaelWD** 2021-10-17 04:37 UTC
