### ISSUE TITLE
v-scroll directive with target are not registered

### ISSUE THREAD

**Issue by aldarund** [vuetifyjs/vuetify-loader#104] opened 2019-11-23 19:27 UTC
```v-scroll:#target="callback"``` - not registered
```v-scroll="callback"``` - registered properly

**Comment by jacekkarczmarczyk** [comment] 2019-11-24 00:58
Duplicate of https://github.com/vuetifyjs/vuetify-loader/issues/99

**Closed by jacekkarczmarczyk** 2019-11-24 00:58 UTC
