### ISSUE TITLE
BUG - Application Load Stuck - Sourcemap

### ISSUE THREAD

**Issue by linspw** [vuetifyjs/vuetify-loader#311] opened 2023-08-26 03:56 UTC
Hello everything is fine?

Some time ago, my Nuxt application started to take a long time to load in google chrome (it practically gets stuck in the page load step), I found it very strange.

I went after logs to identify, and I found a strange behavior in the network. Some Vue files were in "Pending".

![image](https://github.com/vuetifyjs/vuetify-loader/assets/43552865/2d66b9be-d9c9-4382-b4d5-0bb6d98914a0)

And this only happened with Vuetify files.

I went after logs in debbuger in chrome and network:

```sh
 WARN  Sourcemap for "plugin-vuetify:components/VApp/VApp.sass" points to missing source files                                                                           00:40:35
 WARN  Sourcemap for "plugin-vuetify:components/VImg/VImg.sass" points to missing source files                                                                           00:41:21
 WARN  Sourcemap for "plugin-vuetify:labs/VDataTable/VDataTableFooter.sass" points to missing source files                                                               00:41:21
 WARN  Sourcemap for "plugin-vuetify:components/VTabs/VTab.sass" points to missing source files                                                                          00:41:21
 WARN  Sourcemap for "plugin-vuetify:components/VMain/VMain.sass" points to missing source files                                                                         00:41:21
 WARN  Sourcemap for "plugin-vuetify:components/VDivider/VDivider.sass" points to missing source files                                                                   00:41:22
 WARN  Sourcemap for "plugin-vuetify:components/VWindow/VWindow.sass" points to missing source files                                                                     00:41:22
 WARN  Sourcemap for "plugin-vuetify:components/VIcon/VIcon.sass" points to missing source files                                                                         00:41:22
 WARN  Sourcemap for "plugin-vuetify:components/VSheet/VSheet.sass" points to missing source files                                                                       00:41:22
 WARN  Sourcemap for "plugin-vuetify:labs/VDataTable/VDataTable.sass" points to missing source files                                                                     00:41:22
 WARN  Sourcemap for "plugin-vuetify:components/VSwitch/VSwitch.sass" points to missing source files                                                                     00:41:22
 WARN  Sourcemap for "plugin-vuetify:components/VAvatar/VAvatar.sass" points to missing source files                                                                     00:41:22
 WARN  Sourcemap for "plugin-vuetify:components/VTextField/VTextField.sass" points to missing source files                                                               00:41:22
 WARN  Sourcemap for "plugin-vuetify:components/VToolbar/VToolbar.sass" points to missing source files                                                                   00:41:22
 WARN  Sourcemap for "plugin-vuetify:components/VList/VList.sass" points to missing source files                                                                         00:41:22
 WARN  Sourcemap for "plugin-vuetify:components/VCard/VCard.sass" points to missing source files                                                                         00:41:22
 WARN  Sourcemap for "plugin-vuetify:components/VList/VListItem.sass" points to missing source files                                                                     00:41:22
 WARN  Sourcemap for "plugin-vuetify:components/VBtn/VBtn.sass" points to missing source files                                                                           00:41:22
 WARN  Sourcemap for "plugin-vuetify:components/VTabs/VTabs.sass" points to missing source files                                                                         00:41:22
 WARN  Sourcemap for "plugin-vuetify:components/VGrid/VGrid.sass" points to missing source files                                                                         00:41:22
 WARN  Sourcemap for "plugin-vuetify:components/VMenu/VMenu.sass" points to missing source files                                                                         00:41:31
 WARN  Sourcemap for "plugin-vuetify:components/VNavigationDrawer/VNavigationDrawer.sass" points to missing source files                                                 00:41:31
 WARN  Sourcemap for "plugin-vuetify:components/VBtnToggle/VBtnToggle.sass" points to missing source files                                                               00:41:50
 WARN  Sourcemap for "plugin-vuetify:components/VCounter/VCounter.sass" points to missing source files                                                                   00:41:50
 WARN  Sourcemap for "plugin-vuetify:components/VResponsive/VResponsive.sass" points to missing source files                                                             00:41:50
 WARN  Sourcemap for "plugin-vuetify:components/VSlideGroup/VSlideGroup.sass" points to missing source files                                                             00:41:50
 WARN  Sourcemap for "plugin-vuetify:directives/ripple/VRipple.sass" points to missing source files                                                                      00:41:50
 WARN  Sourcemap for "plugin-vuetify:components/VSelectionControl/VSelectionControl.sass" points to missing source files                                                 00:41:50
 WARN  Sourcemap for "plugin-vuetify:components/VInput/VInput.sass" points to missing source files                                                                       00:41:50
 WARN  Sourcemap for "plugin-vuetify:components/VTable/VTable.sass" points to missing source files                                                                       00:41:50
 WARN  Sourcemap for "plugin-vuetify:components/VField/VField.sass" points to missing source files                                                                       00:41:50
 WARN  Sourcemap for "plugin-vuetify:components/VAppBar/VAppBar.sass" points to missing source files                                                                     00:41:54
 WARN  Sourcemap for "plugin-vuetify:components/VBottomNavigation/VBottomNavigation.sass" points to missing source files                                                 00:41:54
 WARN  Sourcemap for "plugin-vuetify:components/VRating/VRating.sass" points to missing source files                                                                     00:42:02
 WARN  Sourcemap for "plugin-vuetify:components/VOverlay/VOverlay.sass" points to missing source files                                                                   00:42:02
 WARN  Sourcemap for "plugin-vuetify:components/VDialog/VDialog.sass" points to missing source files                                                                     00:42:02
 WARN  Sourcemap for "plugin-vuetify:components/VTooltip/VTooltip.sass" points to missing source files                                                                   00:42:13
 WARN  Sourcemap for "plugin-vuetify:components/VCombobox/VCombobox.sass" points to missing source files                                                                 00:42:13
 WARN  Sourcemap for "plugin-vuetify:components/VBtnGroup/VBtnGroup.sass" points to missing source files                                                                 00:42:13
 WARN  Sourcemap for "plugin-vuetify:components/VChip/VChip.sass" points to missing source files                                                                         00:42:13
 WARN  Sourcemap for "plugin-vuetify:components/VCode/VCode.sass" points to missing source files                                                                         00:42:16
 WARN  Sourcemap for "plugin-vuetify:components/VKbd/VKbd.sass" points to missing source files                                                                           00:42:16
 WARN  Sourcemap for "plugin-vuetify:components/VSelectionControlGroup/VSelectionControlGroup.sass" points to missing source files                                       00:42:40
 WARN  Sourcemap for "plugin-vuetify:components/VCheckbox/VCheckbox.sass" points to missing source files                                                                 00:42:40
 WARN  Sourcemap for "plugin-vuetify:components/VMessages/VMessages.sass" points to missing source files                                                                 00:42:40
 WARN  Sourcemap for "plugin-vuetify:components/VTextarea/VTextarea.sass" points to missing source files                                                                 00:42:40
 WARN  Sourcemap for "plugin-vuetify:components/VSelect/VSelect.sass" points to missing source files                                                                     00:42:40
 WARN  Sourcemap for "plugin-vuetify:components/VBreadcrumbs/VBreadcrumbs.sass" points to missing source files                                                           00:42:40
 WARN  Sourcemap for "plugin-vuetify:components/VProgressCircular/VProgressCircular.sass" points to missing source files                                                 00:42:40
 WARN  Sourcemap for "plugin-vuetify:labs/VSkeletonLoader/VSkeletonLoader.sass" points to missing source files                                                           00:42:40
 WARN  Sourcemap for "plugin-vuetify:components/VExpansionPanel/VExpansionPanel.sass" points to missing source files                                                     00:42:40
 WARN  Sourcemap for "plugin-vuetify:components/VBadge/VBadge.sass" points to missing source files                                                                       00:42:50
 WARN  Sourcemap for "plugin-vuetify:components/VAutocomplete/VAutocomplete.sass" points to missing source files                                                         00:42:50
 WARN  Sourcemap for "plugin-vuetify:labs/VBottomSheet/VBottomSheet.sass" points to missing source files                                                                 00:42:50
 WARN  Sourcemap for "plugin-vuetify:components/VSnackbar/VSnackbar.sass" points to missing source files                                                                 00:42:53
 WARN  Sourcemap for "plugin-vuetify:components/VAlert/VAlert.sass" points to missing source files                                                                       00:42:56
 WARN  Sourcemap for "plugin-vuetify:components/VChipGroup/VChipGroup.sass" points to missing source files   
```
And the request action chain came through vite-plugin-vuetify:

![image](https://github.com/vuetifyjs/vuetify-loader/assets/43552865/2ac90623-0cbb-4e3e-bac0-58c6f81f8079)

My current workaround is using firefox.

If you know how to solve it, I'd be very grateful.

I also thank you for your attention.

**Comment by KaelWD** [comment] 2023-08-26 09:04
Duplicate of #290

**Closed by KaelWD** 2023-08-26 09:04 UTC
