### ISSUE TITLE
[Bug Report] <svg-icon>error

### ISSUE THREAD

**Issue by renliquan** [vuetifyjs/vuetify-loader#83] opened 2019-08-26 03:04 UTC
### Environment

**Browsers:** Chrome 75.0.3770.100
**OS:** Mac OS 10.14.6

### Steps to reproduce
Module parse failed: Unexpected token (20:18)
You may need an appropriate loader to handle this file type.
| 
|     if (icon) {
>       vnodes.push(<svg-icon icon-class={icon}/>)
|     }
| 

 @ ./node_modules/vuetify-loader/lib/loader.js!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!.

**Comment by KaelWD** [comment] 2019-08-26 04:38
Duplicate of #79

**Closed by KaelWD** 2019-08-26 04:38 UTC
