### ISSUE TITLE
TypeScript error occurred while importing vite-plugin-vuetify

### ISSUE THREAD

**Issue by w1ndy** [vuetifyjs/vuetify-loader#244] opened 2022-06-21 03:23 UTC
The project was set up from the vue-ts template with vite. TypeScript reports  the following error for ``import vuetify from 'vite-plugin-vuetify'`` in ``vite.config.ts``:
```
This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.
```

I think this issue might be related to this line:
https://github.com/vuetifyjs/vuetify-loader/blob/b3ffbb3c611dc865302fd67c35ca3a126bb2c0df/packages/vite-plugin/src/index.ts#L7

Maybe it should be ``export default function ...``?

**Comment by KaelWD** [comment] 2022-06-21 07:20
Duplicate of #227

**Closed by KaelWD** 2022-06-21 07:20 UTC
