### ISSUE TITLE
installDirectives is not compatible with vuetify 2.x

### ISSUE THREAD

**Issue by husayt** [vuetifyjs/vuetify-loader#52] opened 2019-06-06 02:42 UTC
due to change of casing in export directives in v 2,x installDirectives method stopped working
in vuetify 1.5.x it used to be exported like this
```
export default {
    ClickOutside: ClickOutside,
    Ripple: Ripple,
    Resize: Resize,
    Scroll: Scroll,
    Touch: Touch
};
```
in 2.0
```
export * from './click-outside';
export * from './resize';
export * from './ripple';
export * from './scroll';
export * from './touch';
```
where each of them exports in low case e.g.:
```
export { resize };
export default resize;
```

**Comment by jacekkarczmarczyk** [comment] 2019-07-06 17:51
duplicate of https://github.com/vuetifyjs/vuetify/issues/7684

**Closed by jacekkarczmarczyk** 2019-07-06 17:51 UTC
