### ISSUE TITLE
Identifier 'installComponents' has already been declared

### ISSUE THREAD

**Issue by JeremyWalters** [vuetifyjs/vuetify-loader#19] opened 2018-10-22 07:39 UTC
Vuetify: 1.3.1
vue: 2.5.17 
vue-cli-plugin-vuetify: 0.3.0
vuetif-loader: 1.0.5
Typescript 3.0.1

Hi, I am running a Vue/Typescript/Vuetify(a la carte) project. Upgraded to Vuetify 1.3.1 . Added the Vuetify loader plugin inside `vue.config.js` . I am getting the following error:

```
Module parse failed: Identifier 'installComponents' has already been declared (29:7)
You may need an appropriate loader to handle this file type.
| 
| /* vuetify-loader */
> import installComponents from "!../../../node_modules/vuetify-loader/lib/runtime/installComponents.js"
| import { VAlert } from 'vuetify/lib'
| installComponents(component, {
```

**Comment by KaelWD** [comment] 2018-10-22 11:48
Duplicate of #20

**Closed by KaelWD** 2018-10-22 11:48 UTC

**Comment by Ruchirr** [comment] 2020-04-22 09:15
Please remove buildModules

```
{
  buildModules: [
    // Simple usage
    '@nuxtjs/vuetify',

    // With options
    ['@nuxtjs/vuetify', { /* module options */ }]
  ]
}
```


Add modules, this one is for latest versions
```
modules: [
    '@nuxtjs/vuetify',
  ],
vuetify: {
//what ever options you may like
  },
```
