### ISSUE TITLE
Conflict with vue-router ?

### ISSUE THREAD

**Issue by Alexays** [vuetifyjs/vuetify-loader#18] opened 2018-10-21 22:02 UTC
When updated to latest version i got this error from several contexts
```
Module parse failed: Identifier 'installComponents' has already been declared (42:7)
You may need an appropriate loader to handle this file type.
|
| /* vuetify-loader */
> import installComponents from "!../../../node_modules/vuetify-loader/lib/runtime/installComponents.js"
| import { VBtn } from 'vuetify/lib'
| import { VCard } from 'vuetify/lib'

 @ ./src/router/index.js 10:19-12:20
 @ ./src/main.js
 @ multi ./src/main.js
```

**Comment by KaelWD** [comment] 2018-10-22 12:15
Duplicate of #20

**Closed by KaelWD** 2018-10-22 12:15 UTC
