### ISSUE TITLE
Vite plugin: overriding variables from some components triggers an error

### ISSUE THREAD

**Issue by BreizhReloaded** [vuetifyjs/vuetify-loader#226] opened 2021-12-07 16:16 UTC
Hello again,

I found a new issue, deeply linked to Vuetify itself, so I don't know if that's the right place. The build process crashes when overriding variables of a component referencing variables from an other component. For example:

```scss
// VField.scss
@forward './variables'
@use 'sass:map'
@use 'sass:selector'
@use '../../styles/settings'
@use '../../styles/tools'
@use './variables' as *
@use '../VInput/variables' as *

// Field style
```

```
[vite:css] This variable was not declared with !default in the @used module.
  ╷
5 │   $field-font-size: 0.875rem
  │   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\main.scss 5:3  root stylesheet
file: C:/Users/xxx/my-vue-app/src/main.scss
Error: This variable was not declared with !default in the @used module.
  ╷
5 │   $field-font-size: 0.875rem
  │   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\main.scss 5:3  root stylesheet
error during build:
Error: This variable was not declared with !default in the @used module.
  ╷
5 │   $field-font-size: 0.875rem
  │   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\main.scss 5:3  root stylesheet
    at Object.wrapException (C:\Users\xxx\my-vue-app\node_modules\sass\sass.dart.js:6290:17)
    at _EvaluateVisitor2._async_evaluate0$_assertConfigurationIsEmpty$2$nameInError (C:\Users\xxx\my-vue-app\node_modules\sass\sass.dart.js:67605:15)
    at _EvaluateVisitor2._async_evaluate0$_assertConfigurationIsEmpty$1 (C:\Users\xxx\my-vue-app\node_modules\sass\sass.dart.js:67608:19)
    at C:\Users\xxx\my-vue-app\node_modules\sass\sass.dart.js:68741:27
    at _wrapJsFunctionForAsync_closure.$protected (C:\Users\xxx\my-vue-app\node_modules\sass\sass.dart.js:12048:15)
    at _wrapJsFunctionForAsync_closure.call$2 (C:\Users\xxx\my-vue-app\node_modules\sass\sass.dart.js:26877:12)
    at _awaitOnObject_closure.call$1 (C:\Users\xxx\my-vue-app\node_modules\sass\sass.dart.js:26865:32)
    at Object._rootRunUnary (C:\Users\xxx\my-vue-app\node_modules\sass\sass.dart.js:12422:18)
    at StaticClosure.<anonymous> (C:\Users\xxx\my-vue-app\node_modules\sass\sass.dart.js:94428:16)
    at _CustomZone.runUnary$2$2 (C:\Users\xxx\my-vue-app\node_modules\sass\sass.dart.js:28272:39)
```

I updated my [test project](https://github.com/BreizhReloaded/my-vue-app) for a reproducible case. Commenting `$field-font-size` solves the issue.

**Comment by KaelWD** [comment] 2021-12-08 07:51
Duplicate of https://github.com/vuetifyjs/vuetify/issues/14446

If this won't be fixed in sass we might need a separate file just for the forwards so nothing is duplicated.

**Closed by KaelWD** 2021-12-08 07:51 UTC
