### ISSUE TITLE
A la carte data iterator doesn't work with vuetify content-tag

### ISSUE THREAD

**Issue by javiertury** [vuetifyjs/vuetify-loader#15] opened 2018-10-18 14:26 UTC
I encountered a problem using data iterator with a la carte vuetify-loader. The setup is the following.

```
<v-data-iterator :items="this.items"
                         content-tag="v-layout"
                         :total-items="this.items.length"
                         hide-actions row wrap>
  <v-flex>
    <p>Elements</p>
    <v-layout row wrap>
      ....
    </v-layout>
  </v-flex>
</v-data-iterator>
```

`v-data-iterator` needs `v-layout` as it's the `content-tag`. It shouldn't be a problem since `v-layout` is already used in the slot. However I obtain the following error.

```
Unknown custom element: <v-layout> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```

**Comment by KaelWD** [comment] 2018-10-18 14:33
Duplicate of #9

**Closed by KaelWD** 2018-10-18 14:33 UTC
