### ISSUE TITLE
Vue styleguidist inside Vue template

### ISSUE THREAD

**Issue by MaeseppTarvo** [vuetifyjs/vuetify-loader#55] opened 2019-07-01 12:36 UTC
Hey! Awesome plugin. Just wanted to ask, is it possible to use vue-styleguidist inside template and keep vuetify-loader working?

I am getting the following error: ```Uncaught TypeError: "" is not a function``` if vuetify-loader is enabled and if my .vue file contains the following which is required to have example in vue-styleguidist documentation:

```
<docs>
```vue
  <template>
  </template>
```
</docs>

**Comment by KaelWD** [comment] 2019-07-25 10:03
Duplicate of #47

**Closed by KaelWD** 2019-07-25 10:03 UTC
