### ISSUE TITLE
WARN Sourcemap for "plugin-vuetify: components/VAlert/VAlert.sass" points to missing source files, in treeShaking mode

### ISSUE THREAD

**Issue by hackcharms** [vuetifyjs/vuetify-loader#316] opened 2023-09-29 05:37 UTC
Environment Details
```
vite: 4.4.9 
nuxt: ^3.7.3,
vite-plugin-vuetify: ^1.0.2,
vuetify: ^3.3.16
```

when TreeShaking is enable it throws warning in console (please check the attached image) looks like `plugin-vuetify` is trying to import all sass files
<img width="559" alt="image" src="https://github.com/vuetifyjs/vuetify-loader/assets/48487312/80ef5188-8072-450e-a814-cd5a7b7d3322">

**Comment by KaelWD** [comment] 2023-09-29 05:40
Duplicate of #290

**Closed by KaelWD** 2023-09-29 05:40 UTC
