### ISSUE TITLE
[Bug Report] Conflict with global SCSS in vue.config

### ISSUE THREAD

**Issue by Stegosource** [vuetifyjs/vuetify-loader#75] opened 2019-08-07 18:40 UTC
### Environment

**Browsers:** Chrome 76.0.3809.87
**OS:** Linux x86_64

### Steps to reproduce
Create a globally shared SCSS file at src/assets/scss/_shared.scss, and add the following lines to vue.config.js:

```
css: {
  loaderOptions: {
    sass: {
      data: '@import "@/assets/scss/_shared.scss";'
    }
  }
}
```
This is the recommended way to share SCSS globals like variables, mixins, etc. (https://cli.vuejs.org/guide/css.html#passing-options-to-pre-processor-loaders)

### Expected Behavior
I should be able to provide my shared SCSS to all my components without build errors

### Actual Behavior
Getting an error at build:
```
error  in ./node_modules/vuetify/src/components/VTooltip/VTooltip.sass

Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import ../../styles/styles.sass
                                   ^
      Semicolons aren't allowed in the indented syntax.
  ╷
1 │ @import "@/assets/scss/_shared.scss";
```

### Reproduction Link
<a href="" target="_blank"></a>

**Comment by KaelWD** [comment] 2019-08-08 01:01
Duplicate of https://github.com/vuejs/vue-cli/issues/4116

**Closed by KaelWD** 2019-08-08 01:01 UTC
