### ISSUE TITLE
webpack 5 support

### ISSUE THREAD

**Issue by hmnd** [vuetifyjs/vuetify-loader#136] opened 2020-06-26 05:26 UTC
In webpack/webpack#9138, the RuleSet class being used in [lib/plugin.js](https://github.com/vuetifyjs/vuetify-loader/blob/master/lib/plugin.js) has been refactored and no longer exists. This makes webpack 5 throw a MODULE_NOT_FOUND error when trying to build.

**Comment by KaelWD** [comment] 2020-06-26 07:02
Related: https://github.com/vuejs/vue-loader/pull/1613, https://github.com/JetBrains/svg-sprite-loader/pull/403

**Comment by draeron** [comment] 2020-10-14 19:07
any knowns a workaround for this ?

**Comment by JorisAerts** [comment] 2020-10-16 08:29
Based on the changes on vue-loader, I also modified the plugin.js and created a plugin-webpack4 and plugin-webpack5 and it seems to work at first sight. 

So, is there already someone in the process of fixing this? Is there an official fix pendig?

**Comment by KaelWD** [comment] 2020-10-17 07:26
If you've made the changes already feel free to open a pull request.

**Comment by bloodlit** [comment] 2020-11-06 03:04
Add webpack 5 support #160

**Comment by chamboug** [comment] 2020-11-06 07:57
@bloodlit How is your PR different from mine (https://github.com/vuetifyjs/vuetify-loader/pull/158) created 2 days ago?

**Comment by grbd** [comment] 2020-11-06 14:08
Any news on this?, this would be useful since webpack 5 has inbuilt support for yarn2's pnp
and we have at least 2 pull requests in now for the same thing

**Comment by MaxMls** [comment] 2020-11-07 14:47
The last commit was 3 months ago, perhaps author is currently busy with the transition to version 3 and cannot accept pull requests

**Comment by grbd** [comment] 2020-11-07 19:11
I think I'll need to go back to webpack4 anyways since there's some issues when using web-dev-server with webpack5 in combination with yarn v2 pnp

https://github.com/webpack/webpack-dev-server/issues/2820

**Comment by alekbless** [comment] 2020-11-13 13:39
I want to use this with the new Laravel Mix 6 and webpack 5 support is needed.

**Comment by bloodlit** [comment] 2020-11-14 00:16
@alekbless take the lib folder from the branch  add-webpack5-support

**Comment by martinoppitz** [comment] 2020-12-04 06:50
the same story here:
- https://github.com/vuetifyjs/vuetify-loader/issues/136 and here
- https://github.com/aurelia/aurelia/issues/982 and here
- https://github.com/sveltejs/svelte-loader/pull/136 and so on

Many thanks to Angular for influencing Webpack and the unconsolidated upgrade to v5.

**Comment by glen-84** [comment] 2020-12-06 06:46
> 
> 
> Related: [vuejs/vue-loader#1613](https://github.com/vuejs/vue-loader/pull/1613), [JetBrains/svg-sprite-loader#403](https://github.com/JetBrains/svg-sprite-loader/pull/403)

Both of these PRs have been merged and released.

**Comment by bkhatkov** [comment] 2020-12-06 18:11
Hi guys. Is there any change to get this done? It seems much easier to switch to any other lib than to wait here. Vue added support of WP5 long time ago. Libs should follow as soon as possible. We invested quite a lot to develop our apps using vuetify and now we're just stuck...

**Comment by drrrMikado** [comment] 2020-12-16 10:48
is there any progress?

**Comment by AGDholo** [comment] 2020-12-23 06:15
If you want to use the new es feature, you will have to update vue/cli to version 5, because webpack 4 has issues that prevent vue/cli4 from using these features, e.g. ?

But vuetify only supports webpack4, so it's hard to keep up with modern development.

**Comment by adiramardiani** [comment] 2021-01-05 02:41
@AGDholo 

> But vuetify only supports webpack4, so it's hard to keep up with modern development.

In documentation vuetify not use `only supports` but `version >=4 of Webpack`
![image](https://user-images.githubusercontent.com/8703419/103600450-02e21300-4f3a-11eb-8241-913ddb5165b2.png)

**Comment by AGDholo** [comment] 2021-01-05 02:44
> @AGDholo
> 
> > But vuetify only supports webpack4, so it's hard to keep up with modern development.
> 
> In documentation vuetify not use `only supports` but `version >=4 of Webpack`
> ![image](https://user-images.githubusercontent.com/8703419/103600450-02e21300-4f3a-11eb-8241-913ddb5165b2.png)

@adiramardiani 
I installed vue cli 5 (webpack v5) and added vuetify, which prompts an error and I had to use the compatibility solution (installing webpack v4 again) to get it to work: https://github.com/vuejs/vue-cli/releases/tag/ v5.0.0-alpha.0

**Comment by AGDholo** [comment] 2021-01-05 02:45
> In documentation vuetify not use `only supports` but `version >=4 of Webpack`

@adiramardiani 

I installed vue cli 5 (webpack v5) and added vuetify, which prompts an error and I had to use the compatibility solution (installing webpack v4 again) to get it to work: https://github.com/vuejs/vue-cli/releases/tag/ v5.0.0-alpha.0

**Comment by vstyler96** [comment] 2021-01-12 01:09
I can't still solve my problem, I am still getting this: 
![image](https://user-images.githubusercontent.com/46312870/104256249-7acfa200-5440-11eb-9856-19c346f19326.png)

**Comment by awill1988** [comment] 2021-01-13 16:26
I have a PR #166 which is working for me, it mimics to the `plugin-webpack4/5.js` approach that exists in vue-loader. I think this gets us over the finish line right?

**Comment by vstyler96** [comment] 2021-01-13 21:50
@awill1988 did you check this with laravel mix?

**Comment by awill1988** [comment] 2021-01-13 21:51
I did not

**Comment by vstyler96** [comment] 2021-01-13 22:33
@awill1988 are the custom variables working from webpack config? :o

**Comment by awill1988** [comment] 2021-01-14 01:22
I'm not sure I'm about to publish an example with Vue2 Vuetify with module federation so that is my focus.. this seemed like the easiest lift

**Closed** 2021-01-18 16:31 UTC
Labels: enhancement

**Comment by KaelWD** [comment] 2021-01-18 16:38
[v1.7.0](https://github.com/vuetifyjs/vuetify-loader/releases/tag/v1.7.0) has been published as `vuetify-loader@next`. If you find any problems with webpack 5 please report them in a new issue.

**Comment by tux2nicolae** [comment] 2021-01-18 19:06
Just updated to vuetify-loader@next and getting this

![image](https://user-images.githubusercontent.com/39991250/104954473-f6959580-59d0-11eb-9bd0-586e87d32ce9.png)

**Comment by mathe42** [comment] 2021-01-18 19:36
> If you find any problems with webpack 5 please report them in a new issue.

Create a new issue for that! With a reproduction repro!

**Comment by stefanKuijers** [comment] 2021-02-05 14:21
@tux2nicolae Could you link back to this issue if you create a new issue? Just so I can follow the progress as well. :)

**Comment by tux2nicolae** [comment] 2021-02-05 14:40
@stefanKuijers Actually I didn't created a new issues as the problem may be fixed in `1.7.1` it works for me.

**Comment by bhanuunrivalled** [comment] 2021-03-11 15:59
HI , Iam using `"webpack": "^3.8.1"  `

```
  "vue": "^2.5.9",
    "vue-chart-js": "^1.4.1",
    "vue-chartkick": "^0.2.0",
    "vue-i18n": "^7.3.2",
    "vuetify": "^0.16.4"
```

is it possible for me to update to webpack 5?  or webpack 4? which one is better?

**Comment by kpturner** [comment] 2022-02-15 11:38
> @stefanKuijers Actually I didn't created a new issues as the problem may be fixed in `1.7.1` it works for me.

Why do we think this is fixed in `1.7.1`?  That version still references `webpack/lib/RuleSet` in plugin.js and that does not exist in webpack 5
