### ISSUE TITLE
[Bug Report] v-list-item-icon not working

### ISSUE THREAD

**Issue by bestickley** [vuetifyjs/vuetify-loader#64] opened 2019-07-26 17:22 UTC
### Environment

**Browsers:** Chrome 75.0.3770.142
**OS:** Windows 10

### Steps to reproduce
I cannot reproduce in codepen, so it must be something with my local setup.

### Expected Behavior
v-list-item-icon element should be converted to div with appropriate classes

### Actual Behavior
remains v-list-item-icon element in final html
Error message: Unknown custom element: <v-list-item-icon> - did you register the component correctly? For recursive components, make sure to provide the "name" option

### Reproduction Link
<a href="" target="_blank"></a>

### Other comments
Does anyone have any recommendations for how I can debug? I'm not sure where to start. Does it have to do with vuetify-loader? The VListItemIcon.js file is in vuetify/lib/components/VList directory. I'm using vuetify 2.0.1

**Comment by jacekkarczmarczyk** [comment] 2019-07-26 17:25
Duplicate of https://github.com/vuetifyjs/vuetify/issues/8047

**Closed by jacekkarczmarczyk** 2019-07-26 17:25 UTC
