### ISSUE TITLE
[Bug Report] TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by tad-iizuka** [vuetifyjs/vuetify-loader#102] opened 2019-11-23 11:40 UTC
### Environment

vue: @vue/cli 4.0.5
vuetify-loader: 1.4.0

### Steps to reproduce

1.  vue create debug
2. cd debug
3. vue add vuetify
4. npm run serve

### Expected Behavior

server is running up.

### Actual Behavior

```
> debug@0.1.0 serve /Users/Tadashi/Developer_Firebase/debug
> vue-cli-service serve

 INFO  Starting development server...
 ERROR  TypeError: Cannot read property 'match' of undefined
TypeError: Cannot read property 'match' of undefined
    at VuetifyLoaderPlugin.apply (/Users/Tadashi/Developer_Firebase/debug/node_modules/vuetify-loader/lib/plugin.js:28:29)
    at webpack (/Users/Tadashi/Developer_Firebase/debug/node_modules/webpack/lib/webpack.js:51:13)
    at serve (/Users/Tadashi/Developer_Firebase/debug/node_modules/@vue/cli-service/lib/commands/serve.js:161:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! debug@0.1.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the debug@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Tadashi/.npm/_logs/2019-11-23T10_58_20_903Z-debug.log
```

### Reproduction Link

None

### Other comments

How can I fix or workaround this?  If you need more information, please let me know. Thanks in advance.

BR

**Comment by Geowan** [comment] 2019-11-23 11:53
Am also facing this problem with vuecli

**Comment by matmis** [comment] 2019-11-23 11:54
I'm having the same issue, I tried `npm cache clear --force` but without success.

**Comment by Fallpoint** [comment] 2019-11-23 11:55
Same here on two systems, Win 10

1. System running with:
vue-cli 3.11
vuetify-loader 1.4

2. with:
vue-cli 4.0.5
vuetify-loader 1.4

We already tried @matmis suggestion along with clearing node-modules and running `npm install` again - with no success

**Comment by jacekkarczmarczyk** [comment] 2019-11-23 12:02
Duplicate of https://github.com/vuetifyjs/vuetify-loader/issues/101 (see the issue for possible workaround)

**Closed by jacekkarczmarczyk** 2019-11-23 12:02 UTC
