### ISSUE TITLE
[Bug Report] Breaks when used in laravel mix compilation with webpack configuration

### ISSUE THREAD

**Issue by Geowan** [vuetifyjs/vuetify-loader#73] opened 2019-08-05 09:45 UTC
### Environment

**Browsers:** Chrome 75.0.3770.100
**OS:** Linux x86_64

### Steps to reproduce
I have added the vuetify-loader in webpack mix like

     class VuetifyRules {
       webpackRules() {
        return  {
            test: /\.s(c|a)ss$/,
            use: [
                'vue-style-loader',
                'css-loader',
                {
                    loader: 'sass-loader',
                    options: {
                        implementation: require('sass'),
                        fiber: require('fibers'),
                        indentedSyntax: true // optional
                    }
                }
            ]
        }
    }
      }  

     const VuetifyLoaderPlugin = require('vuetify-loader/lib/plugin'); 
      mix.extend('vuetify', new VuetifyRules());
      mix.setPublicPath('web/');
      mix.js('app/app.js', 'web/app.js').webpackConfig({
       plugins: [
           new VuetifyLoaderPlugin()
        ],
     });

### Expected Behavior
To compile without errors

### Actual Behavior
Throws an error when used in the webpack plugins on laravel mix.
the error is :

     UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at items.forEach.item (/node_modules/vuetify-loader/lib/loader.js:21:60)
    at Set.forEach (<anonymous>)

 By removing  the plugins on laravel mix am getting the error Module build failed: 
    @content($material-light)
   ^
      Invalid CSS after "    @content": expected "}", was "($material-light); "
  which as per the documentation you are supposed to add the vuetify loader plugin

### Reproduction Link
<a href="" target="_blank"></a>

**Comment by KaelWD** [comment] 2019-08-05 11:02
Duplicate of #49

**Closed by KaelWD** 2019-08-05 11:02 UTC
