### ISSUE TITLE
 ERROR  Error: [VuetifyLoaderPlugin Error] No matching rule for vue-loader found. Make sure there is at least one root-level rule that uses vue-loader.

### ISSUE THREAD

**Issue by KellsWorks** [vuetifyjs/vuetify-loader#162] opened 2020-11-25 21:47 UTC
Error: [VuetifyLoaderPlugin Error] No matching rule for vue-loader found.
Make sure there is at least one root-level rule that uses vue-loader.
    at VuetifyLoaderPlugin.apply (C:\Users\KELLS KAMUZU\Desktop\Code Zone\JavaScript\Vue.js\manager-app\node_modules\vuetify-loader\lib\plugin.js:29:13)
    at webpack (C:\Users\KELLS KAMUZU\Desktop\Code Zone\JavaScript\Vue.js\manager-app\node_modules\webpack\lib\webpack.js:51:13)
    at serve (C:\Users\KELLS KAMUZU\Desktop\Code Zone\JavaScript\Vue.js\manager-app\node_modules\@vue\cli-service\lib\commands\serve.js:163:22)   
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! manager-app@0.1.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the manager-app@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\KELLS KAMUZU\AppData\Roaming\npm-cache\_logs\2020-11-25T21_43_55_832Z-debug.log

**Comment by salam0smy** [comment] 2020-12-02 20:03
i'm experiencing the same issue
```
Error: [VuetifyLoaderPlugin Error] No matching rule for vue-loader found.
Make sure there is at least one root-level rule that uses vue-loader.
    at VuetifyLoaderPlugin.apply (PATH_TO_PROJECT/node_modules/vuetify-loader/lib/plugin.js:29:13)
    at webpack (PATH_TO_PROJECT/node_modules/webpack/lib/webpack.js:51:13)
    at Promise (PATH_TO_PROJECT/node_modules/@vue/cli-service/lib/commands/build/index.js:200:5)
    at new Promise (<anonymous>)
    at build (PATH_TO_PROJECT/node_modules/@vue/cli-service/lib/commands/build/index.js:199:10)
```

```
"vue": "^2.6.12",
"vuetify": "^2.3.19",
"@vue/cli-service": "~4.5.6",
"vue-cli-plugin-vuetify": "~2.0.7",
"vuetify-loader": "^1.6.0"

```

**Comment by KaelWD** [comment] 2020-12-03 07:48
Duplicate of #161

**Closed by KaelWD** 2020-12-03 07:48 UTC
