### ISSUE TITLE
Components not injected with content-tag property

### ISSUE THREAD

**Issue by hjhjdev** [vuetifyjs/vuetify-loader#14] opened 2018-10-18 04:41 UTC
When using v-data-iterator with content-tag property enabled, It seems that component is not injected automatically.

I got an error below:
`custom element: <v-layout> - did you register the component correctly? For recursive components, make sure to provide the "name" option. found in`

Will there be any temporary fix for this?

**Comment by hjhjdev** [comment] 2018-10-18 04:44
To confirm, this is my vue.config.js:
`
const VuetifyLoaderPlugin = require('vuetify-loader/lib/plugin')

module.exports = {
    configureWebpack: {
      optimization: {
        splitChunks: {
          chunks: 'all'
        }
      },
      plugins: [
        new VuetifyLoaderPlugin()
      ]
    }
  }`

**Comment by hjhjdev** [comment] 2018-10-18 04:57
Inspecting generated codes, I found out using content-tag changes the tag name, div(default) to v-layout.
Changing `content-tag prop="v-layout"` to `content-class="layout"` solves the issue.

Is this should be considered as a bug? Project without vuetify-loader builds successfully with `content-tag prop="v-layout"`

**Comment by KaelWD** [comment] 2018-10-18 05:02
Duplicate of #9

I'll add this as a warning in the docs

**Closed by KaelWD** 2018-10-18 05:02 UTC
